### PR TITLE
Add Datatables

### PR DESCRIPTION
**Pull request by goronfreeman**
This adds [DataTables](https://datatables.net/) to the site and applies it to the Pocket cores table. As the list of cores continues to grow, the sorting and searching features will become more valuable. The default styles are a bit rough, but I think they are fine for now, and we can improve upon them as we improve the website.

`analogue-pocket.md` was converted to an HTML file, because we need to be able to add attributes to certain elements, and markdown doesn't allow us to do this with tables. This PR also removes the `about` page and the link to it from the site header.

### CODE REVIEW

**Comment by joshcampbell191** [comment]
I spent a little time looking into this one myself and found a few things we can change. I also noticed some strange behavior around the scrollX function. Would you mind if I submitted you a PR?

**Comment by goronfreeman** [comment]
> I spent a little time looking into this one myself and found a few things we can change. I also noticed some strange behavior around the scrollX function. Would you mind if I submitted you a PR?

Feel free!

**Comment by goronfreeman** [comment]
Closing in favor of #14

**Comment by joshcampbell191** [comment]
Looks like GitHub pages doesn't support referencing the theme via the GitHub URL. Looks like we'll have to go with your implementation.

**Pull request closed without merging**
